# deploy-preview.yaml

# Workflow to build and deploy site to Vercel using static files
# Name of Workflow
name: vercel-deploy-pr

# Controls when the action will run. Triggers the workflow on push
# events but only for the develop branch
on:
  pull_request:
    types: [ opened, synchronize ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy-preview"
  deploy-preview:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Make some more metadata available as variables
      id: metadata
      run: |
        if [ ${{github.event_name }} == "pull_request" ]
        then
          echo "::set-output name=DEPLOY_NAME::PR-$(echo $GITHUB_REF | awk -F/ '{ print $3 }')"
        else
          echo "::set-output name=DEPLOY_NAME::BRANCH-${GITHUB_REF##*/}"
        fi

    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive  # Fetch private content
          fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod
          lfs: true

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: ðŸ”¨ Build project
      run: |
        npm ci
        npm run build

    - name: Configure vercel.json
      run: |
        cat > build/vercel.json <<EOF
        {
          "rewrites": [
            {
              "source": "/((?!^/$).*)",
              "destination": "/"
            }
          ]
        }
        EOF

    # Push our generated Hugo site to Vercel
    - name: Deploy testnet to Vercel
      uses: amondnet/vercel-action@v20
      id: vercel-action
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        #github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} #Required
        github-comment: false
        #vercel-args: '--prod' #Optional
        working-directory: build

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      if: ${{ github.event_name == 'pull_request' }}
      with:
        message: 'Vercel PR (merge commit) deploy URL: ${{ steps.vercel-action.outputs.preview-url }}'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
